from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any
from urllib.parse import quote
from urllib.request import Request, urlopen

from boardsight_ai.config import AppConfig


WEEKDAY_INDEX = {
    "monday": 0,
    "tuesday": 1,
    "wednesday": 2,
    "thursday": 3,
    "friday": 4,
    "saturday": 5,
    "sunday": 6,
}


@dataclass
class GitLabSettings:
    base_url: str
    project_id: str
    private_token: str


def _normalize_due_date(text: str) -> str | None:
    lowered = text.lower()
    for name, weekday in WEEKDAY_INDEX.items():
        if name in lowered:
            now = datetime.utcnow()
            days_ahead = (weekday - now.weekday()) % 7
            days_ahead = 7 if days_ahead == 0 else days_ahead
            return (now + timedelta(days=days_ahead)).date().isoformat()
    match = re.search(r"\b(\d{4}-\d{2}-\d{2})\b", text)
    if match:
        return match.group(1)
    return None


def _normalize_slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-") or "item"


def _extract_owner(text: str, fallback: str) -> str:
    match = re.search(r"\b([A-Z][a-z]+)\b", text)
    if match:
        return match.group(1)
    return fallback or "Unassigned"


def _extract_action_clauses(text: str) -> list[dict[str, Any]]:
    normalized = " ".join(str(text or "").split())
    if not normalized:
        return []
    clauses: list[dict[str, Any]] = []
    pattern = re.compile(r"([A-Z][a-z]+)\s+will\s+(.+?)(?=(?:,\s*(?:and\s+)?)?[A-Z][a-z]+\s+will\s+|$)", re.IGNORECASE)
    for match in pattern.finditer(normalized):
        owner = match.group(1)
        body = match.group(2).strip(" ,.")
        clauses.append(
            {
                "owner": owner,
                "body": body,
                "due_date": _normalize_due_date(body),
                "raw_text": match.group(0).strip(),
            }
        )
    return clauses


def build_gitlab_execution_plan(
    source: dict[str, Any],
    *,
    source_kind: str,
    source_id: str,
    meeting_title: str,
    assignee_map: dict[str, int] | None = None,
) -> dict[str, Any]:
    assignee_map = assignee_map or {}
    decisions = list(source.get("decisions", []) or [])
    action_items = list(source.get("action_items", []) or source.get("workflow_model", {}).get("execution_plan", []) or [])
    problems = list(source.get("problems", []) or [])
    discussion_points = list(source.get("discussion_points", []) or [])
    extracted_clauses: list[dict[str, Any]] = []
    for item in decisions:
        extracted_clauses.extend(_extract_action_clauses(str(item.get("text", ""))))
    if not extracted_clauses:
        for item in discussion_points:
            extracted_clauses.extend(_extract_action_clauses(str(item)))
    clause_texts = [clause["raw_text"].lower() for clause in extracted_clauses]

    milestone = {
        "title": meeting_title[:80],
        "description": f"Generated by BoardSight from {source_kind} source {source_id}.",
        "due_date": next((item for item in (_normalize_due_date(" ".join([str(action.get('title', '')), str(action.get('notes', '')), str(action.get('text', ''))])) for action in action_items) if item), None),
    }

    planned_issues: list[dict[str, Any]] = []
    issue_index = 1
    local_key_by_source: dict[str, str] = {}

    for problem in problems:
        problem_text = str(problem.get("text", ""))
        if clause_texts and any(problem_text.lower() in clause_text or clause_text in problem_text.lower() for clause_text in clause_texts):
            continue
        owner = _extract_owner(str(problem.get("text", "")), str(problem.get("speaker", "Unassigned")))
        local_key = f"GL-{issue_index}"
        planned_issues.append(
            {
                "local_key": local_key,
                "kind": "blocker",
                "title": f"Resolve blocker: {str(problem.get('text', ''))[:90]}",
                "description": (
                    f"BoardSight detected this blocker during meeting `{meeting_title}`.\n\n"
                    f"- Source kind: {source_kind}\n"
                    f"- Source id: {source_id}\n"
                    f"- Timestamp: {problem.get('timestamp', 'live')}\n"
                    f"- Speaker: {problem.get('speaker', 'Unknown')}\n"
                    f"- Category: {problem.get('category', 'blocker')}\n"
                    f"- Original statement: {problem.get('text', '')}\n"
                ),
                "owner": owner,
                "assignee_id": assignee_map.get(owner.lower()),
                "due_date": _normalize_due_date(str(problem.get("text", ""))),
                "labels": ["boardsight", "meeting-generated", "blocker"],
                "traceability": {
                    "source_kind": source_kind,
                    "source_id": source_id,
                    "meeting_title": meeting_title,
                    "problem_timestamp": problem.get("timestamp"),
                },
                "dependencies": [],
            }
        )
        local_key_by_source[f"problem:{problem.get('timestamp')}:{_normalize_slug(str(problem.get('text', '')))}"] = local_key
        issue_index += 1

    for action in action_items:
        action_text = " ".join(str(action.get(key, "")) for key in ("title", "notes", "text"))
        if extracted_clauses and len(re.findall(r"\b[A-Z][a-z]+\s+will\b", action_text)) > 1:
            continue
        owner = _extract_owner(action_text, str(action.get("owner", "Unassigned")))
        local_key = f"GL-{issue_index}"
        decision_id = str(action.get("decision_id", ""))
        dependency_keys = []
        lowered = action_text.lower()
        if "before" in lowered or "depends" in lowered or "after" in lowered:
            dependency_keys = [item["local_key"] for item in planned_issues if item["kind"] == "blocker"][:1]
        planned_issues.append(
            {
                "local_key": local_key,
                "kind": "action-item",
                "title": str(action.get("title", f"Action item {issue_index}"))[:120],
                "description": (
                    f"Generated by BoardSight from meeting `{meeting_title}`.\n\n"
                    f"- Source kind: {source_kind}\n"
                    f"- Source id: {source_id}\n"
                    f"- Decision id: {decision_id or 'n/a'}\n"
                    f"- Execution order: {action.get('execution_order', issue_index)}\n"
                    f"- Owner: {owner}\n"
                    f"- Original task notes: {action.get('notes', '')}\n"
                    f"- Discussion points: {json.dumps(discussion_points[:3])}\n"
                ),
                "owner": owner,
                "assignee_id": assignee_map.get(owner.lower()),
                "due_date": _normalize_due_date(action_text),
                "labels": ["boardsight", "meeting-generated", "action-item"],
                "traceability": {
                    "source_kind": source_kind,
                    "source_id": source_id,
                    "meeting_title": meeting_title,
                    "decision_id": decision_id,
                },
                "dependencies": dependency_keys,
            }
        )
        if decision_id:
            local_key_by_source[f"decision:{decision_id}"] = local_key
        issue_index += 1

    for clause in extracted_clauses:
        if any(clause["body"].lower() in str(issue.get("title", "")).lower() or clause["owner"].lower() == str(issue.get("owner", "")).lower() for issue in planned_issues):
            continue
        local_key = f"GL-{issue_index}"
        planned_issues.append(
            {
                "local_key": local_key,
                "kind": "action-item",
                "title": f"{clause['owner']}: {clause['body'][:100]}",
                "description": (
                    f"Generated by BoardSight from meeting `{meeting_title}`.\n\n"
                    f"- Source kind: {source_kind}\n"
                    f"- Source id: {source_id}\n"
                    f"- Extracted owner: {clause['owner']}\n"
                    f"- Original statement: {clause['raw_text']}\n"
                ),
                "owner": clause["owner"],
                "assignee_id": assignee_map.get(clause["owner"].lower()),
                "due_date": clause["due_date"],
                "labels": ["boardsight", "meeting-generated", "action-item"],
                "traceability": {
                    "source_kind": source_kind,
                    "source_id": source_id,
                    "meeting_title": meeting_title,
                    "source_statement": clause["raw_text"],
                },
                "dependencies": [],
            }
        )
        issue_index += 1

    ordered_action_issues = [issue for issue in planned_issues if issue["kind"] == "action-item"]
    for index, issue in enumerate(ordered_action_issues):
        lowered = f"{issue.get('title', '')} {issue.get('description', '')}".lower()
        if "before that" in lowered or "before this" in lowered:
            if index > 0:
                dependent_issue = ordered_action_issues[max(0, index - 1)]
                if issue["local_key"] not in dependent_issue["dependencies"]:
                    dependent_issue["dependencies"].append(issue["local_key"])

    dependency_links: list[dict[str, str]] = []
    for issue in planned_issues:
        for dependency in issue.get("dependencies", []):
            dependency_links.append(
                {
                    "source_local_key": dependency,
                    "target_local_key": issue["local_key"],
                    "link_type": "blocks",
                }
            )

    return {
        "source_kind": source_kind,
        "source_id": source_id,
        "meeting_title": meeting_title,
        "milestone": milestone,
        "issues": planned_issues,
        "issue_links": dependency_links,
        "traceability": {
            "generated_at": datetime.utcnow().isoformat() + "Z",
            "decision_count": len(decisions),
            "problem_count": len(problems),
            "action_count": len(action_items),
        },
    }


def _gitlab_settings(config: AppConfig, overrides: dict[str, Any] | None = None) -> GitLabSettings | None:
    overrides = overrides or {}
    base_url = str(overrides.get("base_url") or config.gitlab_base_url or "").strip()
    project_id = str(overrides.get("project_id") or config.gitlab_project_id or "").strip()
    token = str(overrides.get("private_token") or config.gitlab_private_token or "").strip()
    if not base_url or not project_id or not token:
        return None
    return GitLabSettings(base_url=base_url.rstrip("/"), project_id=project_id, private_token=token)


def _request_json(settings: GitLabSettings, path: str, method: str = "GET", payload: dict[str, Any] | None = None) -> dict[str, Any] | list[Any]:
    url = f"{settings.base_url}/api/v4{path}"
    body = None
    headers = {
        "PRIVATE-TOKEN": settings.private_token,
        "Content-Type": "application/json",
    }
    if payload is not None:
        body = json.dumps(payload).encode("utf-8")
    request = Request(url, data=body, headers=headers, method=method)
    with urlopen(request, timeout=60) as response:
        raw = response.read().decode("utf-8")
    return json.loads(raw) if raw else {}


def _ensure_milestone(settings: GitLabSettings, plan: dict[str, Any]) -> dict[str, Any] | None:
    milestone = plan.get("milestone") or {}
    title = str(milestone.get("title") or "").strip()
    if not title:
        return None
    encoded_project = quote(settings.project_id, safe="")
    milestones = _request_json(settings, f"/projects/{encoded_project}/milestones")
    if isinstance(milestones, list):
        for item in milestones:
            if str(item.get("title", "")).strip().lower() == title.lower():
                return item
    payload = {
        "title": title,
        "description": milestone.get("description") or "",
    }
    if milestone.get("due_date"):
        payload["due_date"] = milestone["due_date"]
    return _request_json(settings, f"/projects/{encoded_project}/milestones", "POST", payload)


def sync_plan_to_gitlab(
    plan: dict[str, Any],
    config: AppConfig,
    *,
    connection_overrides: dict[str, Any] | None = None,
) -> dict[str, Any]:
    settings = _gitlab_settings(config, connection_overrides)
    if settings is None:
        return {
            "status": "dry-run-only",
            "reason": "GitLab credentials or project settings are missing.",
            "created_issues": [],
            "created_links": [],
        }

    encoded_project = quote(settings.project_id, safe="")
    milestone = _ensure_milestone(settings, plan)
    milestone_id = milestone.get("id") if isinstance(milestone, dict) else None

    created_issues: list[dict[str, Any]] = []
    iid_by_local_key: dict[str, int] = {}
    for issue in plan.get("issues", []):
        payload = {
            "title": issue["title"],
            "description": issue["description"],
            "labels": ",".join(issue.get("labels", [])),
        }
        if milestone_id is not None:
            payload["milestone_id"] = milestone_id
        if issue.get("due_date"):
            payload["due_date"] = issue["due_date"]
        if issue.get("assignee_id"):
            payload["assignee_ids"] = [issue["assignee_id"]]
        created = _request_json(settings, f"/projects/{encoded_project}/issues", "POST", payload)
        iid = int(created.get("iid"))
        iid_by_local_key[issue["local_key"]] = iid
        created_issues.append(
            {
                "local_key": issue["local_key"],
                "iid": iid,
                "web_url": created.get("web_url"),
                "title": created.get("title"),
            }
        )

    created_links: list[dict[str, Any]] = []
    for link in plan.get("issue_links", []):
        source_iid = iid_by_local_key.get(link["source_local_key"])
        target_iid = iid_by_local_key.get(link["target_local_key"])
        if source_iid is None or target_iid is None:
            continue
        created = _request_json(
            settings,
            f"/projects/{encoded_project}/issues/{source_iid}/links",
            "POST",
            {
                "target_project_id": settings.project_id,
                "target_issue_iid": target_iid,
                "link_type": link.get("link_type", "blocks"),
            },
        )
        created_links.append(
            {
                "source_issue_iid": source_iid,
                "target_issue_iid": target_iid,
                "link_type": created.get("link_type"),
            }
        )

    return {
        "status": "synced",
        "project_id": settings.project_id,
        "milestone": milestone,
        "created_issues": created_issues,
        "created_links": created_links,
    }
